export const REGISTER_REQUEST = 'USER/REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'USER/REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'USER/REGISTER_FAILURE'

export const LOGIN_REQUEST = 'USER/LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'USER/LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'USER/LOGIN_FAILURE'

export const TOURS_REQUEST = 'TOURS/TOURS_REQUEST'
export const TOURS_SUCCESS = 'TOURS/TOURS_SUCCESS'
export const TOURS_FAILURE = 'TOURS/TOURS_FAILURE'

export const TOUR_REQUEST = 'TOUR/TOUR_REQUEST'
export const TOUR_SUCCESS = 'TOUR/TOUR_SUCCESS'
export const TOUR_FAILURE = 'TOUR/TOUR_FAILURE'

export const LOGOUT = 'USER/LOGOUT'

export const SELECT_LANGUAGES = 'LANGUAGES/SELECT_LANGUAGES'

